// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcDistsArma
arma::mat calcDistsArma(arma::mat coordsArma);
RcppExport SEXP _NSD_calcDistsArma(SEXP coordsArmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type coordsArma(coordsArmaSEXP);
    rcpp_result_gen = Rcpp::wrap(calcDistsArma(coordsArma));
    return rcpp_result_gen;
END_RCPP
}
// H0functionArma
arma::mat H0functionArma(double phi, arma::mat dists);
RcppExport SEXP _NSD_H0functionArma(SEXP phiSEXP, SEXP distsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dists(distsSEXP);
    rcpp_result_gen = Rcpp::wrap(H0functionArma(phi, dists));
    return rcpp_result_gen;
END_RCPP
}
// choleskyEfficient
arma::mat choleskyEfficient(arma::mat Amat);
RcppExport SEXP _NSD_choleskyEfficient(SEXP AmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Amat(AmatSEXP);
    rcpp_result_gen = Rcpp::wrap(choleskyEfficient(Amat));
    return rcpp_result_gen;
END_RCPP
}
// NSDmodel
NumericMatrix NSDmodel(int nIter, int nThin, List yData, List xData, List xPred, NumericMatrix coordsData, NumericMatrix coordsPred, List By, List Bx, NumericMatrix ByPred, List BxPred, double phiAlpha, double phiBeta, double aAlpha, double bAlpha, double aBeta, double bBeta, double aY, double bY, double aC, double bC, double aX, double bX, NumericVector muD, NumericMatrix SigmaD, double sigmaAlphaPrecInit, double sigmaBetaPrecInit, double sigmaYPrecInit, double sigmaCPrecInit, NumericMatrix alphaInit, NumericMatrix betaInit, NumericMatrix cInit, double sigmaXPrecInit, NumericMatrix dInit);
RcppExport SEXP _NSD_NSDmodel(SEXP nIterSEXP, SEXP nThinSEXP, SEXP yDataSEXP, SEXP xDataSEXP, SEXP xPredSEXP, SEXP coordsDataSEXP, SEXP coordsPredSEXP, SEXP BySEXP, SEXP BxSEXP, SEXP ByPredSEXP, SEXP BxPredSEXP, SEXP phiAlphaSEXP, SEXP phiBetaSEXP, SEXP aAlphaSEXP, SEXP bAlphaSEXP, SEXP aBetaSEXP, SEXP bBetaSEXP, SEXP aYSEXP, SEXP bYSEXP, SEXP aCSEXP, SEXP bCSEXP, SEXP aXSEXP, SEXP bXSEXP, SEXP muDSEXP, SEXP SigmaDSEXP, SEXP sigmaAlphaPrecInitSEXP, SEXP sigmaBetaPrecInitSEXP, SEXP sigmaYPrecInitSEXP, SEXP sigmaCPrecInitSEXP, SEXP alphaInitSEXP, SEXP betaInitSEXP, SEXP cInitSEXP, SEXP sigmaXPrecInitSEXP, SEXP dInitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< List >::type yData(yDataSEXP);
    Rcpp::traits::input_parameter< List >::type xData(xDataSEXP);
    Rcpp::traits::input_parameter< List >::type xPred(xPredSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coordsData(coordsDataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coordsPred(coordsPredSEXP);
    Rcpp::traits::input_parameter< List >::type By(BySEXP);
    Rcpp::traits::input_parameter< List >::type Bx(BxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ByPred(ByPredSEXP);
    Rcpp::traits::input_parameter< List >::type BxPred(BxPredSEXP);
    Rcpp::traits::input_parameter< double >::type phiAlpha(phiAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type phiBeta(phiBetaSEXP);
    Rcpp::traits::input_parameter< double >::type aAlpha(aAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type bAlpha(bAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type aBeta(aBetaSEXP);
    Rcpp::traits::input_parameter< double >::type bBeta(bBetaSEXP);
    Rcpp::traits::input_parameter< double >::type aY(aYSEXP);
    Rcpp::traits::input_parameter< double >::type bY(bYSEXP);
    Rcpp::traits::input_parameter< double >::type aC(aCSEXP);
    Rcpp::traits::input_parameter< double >::type bC(bCSEXP);
    Rcpp::traits::input_parameter< double >::type aX(aXSEXP);
    Rcpp::traits::input_parameter< double >::type bX(bXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type muD(muDSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type SigmaD(SigmaDSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaAlphaPrecInit(sigmaAlphaPrecInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaBetaPrecInit(sigmaBetaPrecInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaYPrecInit(sigmaYPrecInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaCPrecInit(sigmaCPrecInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alphaInit(alphaInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type betaInit(betaInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cInit(cInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaXPrecInit(sigmaXPrecInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dInit(dInitSEXP);
    rcpp_result_gen = Rcpp::wrap(NSDmodel(nIter, nThin, yData, xData, xPred, coordsData, coordsPred, By, Bx, ByPred, BxPred, phiAlpha, phiBeta, aAlpha, bAlpha, aBeta, bBeta, aY, bY, aC, bC, aX, bX, muD, SigmaD, sigmaAlphaPrecInit, sigmaBetaPrecInit, sigmaYPrecInit, sigmaCPrecInit, alphaInit, betaInit, cInit, sigmaXPrecInit, dInit));
    return rcpp_result_gen;
END_RCPP
}
// NSDmodelMulti
NumericMatrix NSDmodelMulti(int nIter, int nThin, List yData, List xData, List zData, List xPred, List zPred, NumericMatrix coordsData, NumericMatrix coordsPred, List By, List Bx, List Bz, NumericMatrix ByPred, List BxPred, List BzPred, double phiAlpha, double phiBeta, double phiGamma, double aAlpha, double bAlpha, double aBeta, double bBeta, double aGamma, double bGamma, double aY, double bY, double aC, double bC, double aX, double bX, double aZ, double bZ, NumericVector muD, NumericMatrix SigmaD, NumericVector muE, NumericMatrix SigmaE, double sigmaAlphaPrecInit, double sigmaBetaPrecInit, double sigmaGammaPrecInit, double sigmaYPrecInit, double sigmaCPrecInit, NumericMatrix alphaInit, NumericMatrix betaInit, NumericMatrix gammaInit, NumericMatrix cInit, double sigmaXPrecInit, double sigmaZPrecInit, NumericMatrix dInit, NumericMatrix eInit);
RcppExport SEXP _NSD_NSDmodelMulti(SEXP nIterSEXP, SEXP nThinSEXP, SEXP yDataSEXP, SEXP xDataSEXP, SEXP zDataSEXP, SEXP xPredSEXP, SEXP zPredSEXP, SEXP coordsDataSEXP, SEXP coordsPredSEXP, SEXP BySEXP, SEXP BxSEXP, SEXP BzSEXP, SEXP ByPredSEXP, SEXP BxPredSEXP, SEXP BzPredSEXP, SEXP phiAlphaSEXP, SEXP phiBetaSEXP, SEXP phiGammaSEXP, SEXP aAlphaSEXP, SEXP bAlphaSEXP, SEXP aBetaSEXP, SEXP bBetaSEXP, SEXP aGammaSEXP, SEXP bGammaSEXP, SEXP aYSEXP, SEXP bYSEXP, SEXP aCSEXP, SEXP bCSEXP, SEXP aXSEXP, SEXP bXSEXP, SEXP aZSEXP, SEXP bZSEXP, SEXP muDSEXP, SEXP SigmaDSEXP, SEXP muESEXP, SEXP SigmaESEXP, SEXP sigmaAlphaPrecInitSEXP, SEXP sigmaBetaPrecInitSEXP, SEXP sigmaGammaPrecInitSEXP, SEXP sigmaYPrecInitSEXP, SEXP sigmaCPrecInitSEXP, SEXP alphaInitSEXP, SEXP betaInitSEXP, SEXP gammaInitSEXP, SEXP cInitSEXP, SEXP sigmaXPrecInitSEXP, SEXP sigmaZPrecInitSEXP, SEXP dInitSEXP, SEXP eInitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< int >::type nThin(nThinSEXP);
    Rcpp::traits::input_parameter< List >::type yData(yDataSEXP);
    Rcpp::traits::input_parameter< List >::type xData(xDataSEXP);
    Rcpp::traits::input_parameter< List >::type zData(zDataSEXP);
    Rcpp::traits::input_parameter< List >::type xPred(xPredSEXP);
    Rcpp::traits::input_parameter< List >::type zPred(zPredSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coordsData(coordsDataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coordsPred(coordsPredSEXP);
    Rcpp::traits::input_parameter< List >::type By(BySEXP);
    Rcpp::traits::input_parameter< List >::type Bx(BxSEXP);
    Rcpp::traits::input_parameter< List >::type Bz(BzSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ByPred(ByPredSEXP);
    Rcpp::traits::input_parameter< List >::type BxPred(BxPredSEXP);
    Rcpp::traits::input_parameter< List >::type BzPred(BzPredSEXP);
    Rcpp::traits::input_parameter< double >::type phiAlpha(phiAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type phiBeta(phiBetaSEXP);
    Rcpp::traits::input_parameter< double >::type phiGamma(phiGammaSEXP);
    Rcpp::traits::input_parameter< double >::type aAlpha(aAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type bAlpha(bAlphaSEXP);
    Rcpp::traits::input_parameter< double >::type aBeta(aBetaSEXP);
    Rcpp::traits::input_parameter< double >::type bBeta(bBetaSEXP);
    Rcpp::traits::input_parameter< double >::type aGamma(aGammaSEXP);
    Rcpp::traits::input_parameter< double >::type bGamma(bGammaSEXP);
    Rcpp::traits::input_parameter< double >::type aY(aYSEXP);
    Rcpp::traits::input_parameter< double >::type bY(bYSEXP);
    Rcpp::traits::input_parameter< double >::type aC(aCSEXP);
    Rcpp::traits::input_parameter< double >::type bC(bCSEXP);
    Rcpp::traits::input_parameter< double >::type aX(aXSEXP);
    Rcpp::traits::input_parameter< double >::type bX(bXSEXP);
    Rcpp::traits::input_parameter< double >::type aZ(aZSEXP);
    Rcpp::traits::input_parameter< double >::type bZ(bZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type muD(muDSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type SigmaD(SigmaDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type muE(muESEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type SigmaE(SigmaESEXP);
    Rcpp::traits::input_parameter< double >::type sigmaAlphaPrecInit(sigmaAlphaPrecInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaBetaPrecInit(sigmaBetaPrecInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaGammaPrecInit(sigmaGammaPrecInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaYPrecInit(sigmaYPrecInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaCPrecInit(sigmaCPrecInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alphaInit(alphaInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type betaInit(betaInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type gammaInit(gammaInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cInit(cInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaXPrecInit(sigmaXPrecInitSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaZPrecInit(sigmaZPrecInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dInit(dInitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eInit(eInitSEXP);
    rcpp_result_gen = Rcpp::wrap(NSDmodelMulti(nIter, nThin, yData, xData, zData, xPred, zPred, coordsData, coordsPred, By, Bx, Bz, ByPred, BxPred, BzPred, phiAlpha, phiBeta, phiGamma, aAlpha, bAlpha, aBeta, bBeta, aGamma, bGamma, aY, bY, aC, bC, aX, bX, aZ, bZ, muD, SigmaD, muE, SigmaE, sigmaAlphaPrecInit, sigmaBetaPrecInit, sigmaGammaPrecInit, sigmaYPrecInit, sigmaCPrecInit, alphaInit, betaInit, gammaInit, cInit, sigmaXPrecInit, sigmaZPrecInit, dInit, eInit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NSD_calcDistsArma", (DL_FUNC) &_NSD_calcDistsArma, 1},
    {"_NSD_H0functionArma", (DL_FUNC) &_NSD_H0functionArma, 2},
    {"_NSD_choleskyEfficient", (DL_FUNC) &_NSD_choleskyEfficient, 1},
    {"_NSD_NSDmodel", (DL_FUNC) &_NSD_NSDmodel, 34},
    {"_NSD_NSDmodelMulti", (DL_FUNC) &_NSD_NSDmodelMulti, 49},
    {NULL, NULL, 0}
};

RcppExport void R_init_NSD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
