# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcDistsArma <- function(coordsArma) {
    .Call(`_NSD_calcDistsArma`, coordsArma)
}

H0functionArma <- function(phi, dists) {
    .Call(`_NSD_H0functionArma`, phi, dists)
}

choleskyEfficient <- function(Amat) {
    .Call(`_NSD_choleskyEfficient`, Amat)
}

NSDmodel <- function(nIter, nThin, yData, xData, xPred, coordsData, coordsPred, By, Bx, ByPred, BxPred, phiAlpha, phiBeta, aAlpha, bAlpha, aBeta, bBeta, aY, bY, aC, bC, aX, bX, muD, SigmaD, sigmaAlphaPrecInit, sigmaBetaPrecInit, sigmaYPrecInit, sigmaCPrecInit, alphaInit, betaInit, cInit, sigmaXPrecInit, dInit) {
    .Call(`_NSD_NSDmodel`, nIter, nThin, yData, xData, xPred, coordsData, coordsPred, By, Bx, ByPred, BxPred, phiAlpha, phiBeta, aAlpha, bAlpha, aBeta, bBeta, aY, bY, aC, bC, aX, bX, muD, SigmaD, sigmaAlphaPrecInit, sigmaBetaPrecInit, sigmaYPrecInit, sigmaCPrecInit, alphaInit, betaInit, cInit, sigmaXPrecInit, dInit)
}

NSDmodelMulti <- function(nIter, nThin, yData, xData, zData, xPred, zPred, coordsData, coordsPred, By, Bx, Bz, ByPred, BxPred, BzPred, phiAlpha, phiBeta, phiGamma, aAlpha, bAlpha, aBeta, bBeta, aGamma, bGamma, aY, bY, aC, bC, aX, bX, aZ, bZ, muD, SigmaD, muE, SigmaE, sigmaAlphaPrecInit, sigmaBetaPrecInit, sigmaGammaPrecInit, sigmaYPrecInit, sigmaCPrecInit, alphaInit, betaInit, gammaInit, cInit, sigmaXPrecInit, sigmaZPrecInit, dInit, eInit) {
    .Call(`_NSD_NSDmodelMulti`, nIter, nThin, yData, xData, zData, xPred, zPred, coordsData, coordsPred, By, Bx, Bz, ByPred, BxPred, BzPred, phiAlpha, phiBeta, phiGamma, aAlpha, bAlpha, aBeta, bBeta, aGamma, bGamma, aY, bY, aC, bC, aX, bX, aZ, bZ, muD, SigmaD, muE, SigmaE, sigmaAlphaPrecInit, sigmaBetaPrecInit, sigmaGammaPrecInit, sigmaYPrecInit, sigmaCPrecInit, alphaInit, betaInit, gammaInit, cInit, sigmaXPrecInit, sigmaZPrecInit, dInit, eInit)
}

